[phases.setup]
nixPkgs = ["python311", "nodejs-18_x", "gcc", "g++"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "npm install"
]

[phases.build]
cmds = ["python migrate_db.py || echo 'Migration skipped'"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 300 --log-level info"
