"""Pick a lighter LOD for phones on the read-only viewer and the embed page.

LODs (ModelLOD rows + model_lodN.glb, generated by converters/lod_generator.py)
are simplified copies of model.glb. Editing always operates on model.glb; this
only decides which file a *viewing* page starts with. Any rewrite of model.glb
invalidates the LOD rows (version_manager.invalidate_lods), and a file older
than model.glb is treated as stale here as a second guard.
"""

import os
import re

from models import ModelLOD

MOBILE_UA_RE = re.compile(
    r"Android|iPhone|iPad|iPod|Mobile|Windows Phone|Opera Mini|webOS", re.IGNORECASE
)
# Mobile gets the best-looking LOD at or below this simplification ratio
# (or the lightest one when every LOD is heavier than that).
MOBILE_LOD_RATIO = 0.5
# Tolerated clock/ordering skew between model.glb and the LOD file (seconds).
FRESHNESS_SKEW = 2.0


def is_mobile_user_agent(user_agent):
    return bool(user_agent and MOBILE_UA_RE.search(user_agent))


def _is_fresh(lod, glb_path, glb_size):
    path = os.path.join(os.path.dirname(glb_path), os.path.basename(lod.filename))
    try:
        lod_size = os.path.getsize(path)
        if lod_size <= 0 or (glb_size and lod_size >= glb_size):
            return False
        return os.path.getmtime(path) + FRESHNESS_SKEW >= os.path.getmtime(glb_path)
    except OSError:
        return False


def pick_lod(model, user_agent, override=None):
    """The ModelLOD to start a viewing page with, or None for the full model.

    None when the device is not a phone/tablet, the visitor asked for the full
    model (override == "full"), no LOD exists, or the LOD is missing/stale.
    """
    if override == "full" or not is_mobile_user_agent(user_agent):
        return None
    glb_path = model.glb_path
    if not glb_path or not os.path.isfile(glb_path):
        return None
    glb_size = os.path.getsize(glb_path)
    lods = (
        ModelLOD.query.filter_by(model_id=model.id)
        .order_by(ModelLOD.ratio.desc())
        .all()
    )
    fresh = [lod for lod in lods if _is_fresh(lod, glb_path, glb_size)]
    if not fresh:
        return None
    for lod in fresh:  # highest ratio first
        if lod.ratio <= MOBILE_LOD_RATIO:
            return lod
    return fresh[-1]
