"""add webar_ai_job for Meshy generation tracking

Revision ID: 2b7a25cad39b
Revises: e26f30fb4560
Create Date: 2026-06-10 21:10:36.698984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7a25cad39b'
down_revision = 'e26f30fb4560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webar_ai_job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('meshy_preview_id', sa.String(length=80), nullable=True),
    sa.Column('meshy_refine_id', sa.String(length=80), nullable=True),
    sa.Column('meshy_image_id', sa.String(length=80), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['webar_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webar_ai_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webar_ai_job_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webar_ai_job_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webar_ai_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webar_ai_job_user_id'))
        batch_op.drop_index(batch_op.f('ix_webar_ai_job_created_at'))

    op.drop_table('webar_ai_job')
    # ### end Alembic commands ###
