"""baseline: full schema

Revision ID: 3a81971f8f25
Revises: 
Create Date: 2026-06-10 13:28:47.837217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a81971f8f25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ai_generation_job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('meshy_preview_id', sa.String(length=80), nullable=True),
    sa.Column('meshy_refine_id', sa.String(length=80), nullable=True),
    sa.Column('meshy_image_id', sa.String(length=80), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversion_job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversion_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversion_job_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversion_job_status'), ['status'], unique=False)

    op.create_table('folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['folder.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user_model',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('usdz_filename', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('vertices', sa.Integer(), nullable=True),
    sa.Column('faces', sa.Integer(), nullable=True),
    sa.Column('is_watertight', sa.Boolean(), nullable=True),
    sa.Column('bounds', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('qr_code', sa.String(length=255), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('original_dimensions', sa.JSON(), nullable=True),
    sa.Column('cumulative_scale', sa.Float(), nullable=True),
    sa.Column('hotspots_visible', sa.Boolean(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camera_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('orbit_theta', sa.Float(), nullable=False),
    sa.Column('orbit_phi', sa.Float(), nullable=False),
    sa.Column('orbit_radius', sa.Float(), nullable=False),
    sa.Column('target_x', sa.Float(), nullable=True),
    sa.Column('target_y', sa.Float(), nullable=True),
    sa.Column('target_z', sa.Float(), nullable=True),
    sa.Column('fov', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_hotspot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('hotspot_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('position_z', sa.Float(), nullable=False),
    sa.Column('normal_x', sa.Float(), nullable=True),
    sa.Column('normal_y', sa.Float(), nullable=True),
    sa.Column('normal_z', sa.Float(), nullable=True),
    sa.Column('camera_view_id', sa.String(length=50), nullable=True),
    sa.Column('camera_orbit_theta', sa.Float(), nullable=True),
    sa.Column('camera_orbit_phi', sa.Float(), nullable=True),
    sa.Column('camera_orbit_radius', sa.Float(), nullable=True),
    sa.Column('camera_target_x', sa.Float(), nullable=True),
    sa.Column('camera_target_y', sa.Float(), nullable=True),
    sa.Column('camera_target_z', sa.Float(), nullable=True),
    sa.Column('camera_fov', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['user_model.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_save',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['user_model.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('operation_details', sa.JSON(), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('vertices', sa.Integer(), nullable=True),
    sa.Column('faces', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_version')
    op.drop_table('model_save')
    op.drop_table('model_like')
    op.drop_table('model_hotspot')
    op.drop_table('camera_view')
    op.drop_table('user_model')
    op.drop_table('folder')
    with op.batch_alter_table('conversion_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversion_job_status'))
        batch_op.drop_index(batch_op.f('ix_conversion_job_created_at'))

    op.drop_table('conversion_job')
    op.drop_table('ai_generation_job')
    op.drop_table('user')
    # ### end Alembic commands ###
