"""initial schema: user, folder, model3d, conversion_job

Revision ID: 81c62a7190b6
Revises: 
Create Date: 2026-06-10 20:42:59.916823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c62a7190b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('conversion_job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversion_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversion_job_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversion_job_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversion_job_user_id'), ['user_id'], unique=False)

    op.create_table('folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_folder_user_name')
    )
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_folder_user_id'), ['user_id'], unique=False)

    op.create_table('model3d',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_format', sa.String(length=10), nullable=False),
    sa.Column('glb_filename', sa.String(length=255), nullable=False),
    sa.Column('usdz_filename', sa.String(length=255), nullable=True),
    sa.Column('qr_filename', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('vertices', sa.Integer(), nullable=True),
    sa.Column('faces', sa.Integer(), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model3d', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model3d_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model3d_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model3d_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model3d', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model3d_user_id'))
        batch_op.drop_index(batch_op.f('ix_model3d_folder_id'))
        batch_op.drop_index(batch_op.f('ix_model3d_created_at'))

    op.drop_table('model3d')
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_folder_user_id'))

    op.drop_table('folder')
    with op.batch_alter_table('conversion_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversion_job_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversion_job_status'))
        batch_op.drop_index(batch_op.f('ix_conversion_job_created_at'))

    op.drop_table('conversion_job')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
